[package]
name = "multi-threading"
version = "0.1.0"
authors = ["Ellie Xu <47287801+ellie-xyb@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"